// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC51vEXgWVlW5pTlirUbfMMXQu76tE475k',
    appId: '1:503588097549:android:544b912c6b1a1c1018cf44',
    messagingSenderId: '503588097549',
    projectId: 'petdatinglove',
    storageBucket: 'petdatinglove.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxFSepW1XpNxMxBPGSvwsxii12JhKlXak',
    appId: '1:503588097549:ios:6d7d62c34dd0f68618cf44',
    messagingSenderId: '503588097549',
    projectId: 'petdatinglove',
    storageBucket: 'petdatinglove.firebasestorage.app',
    iosBundleId: 'kr.mooca.petdate',
    iosClientId:
        '503588097549-q4pse24bn7vo50fvc7uuis4eb447p4qh.apps.googleusercontent.com',
  );

  /// Web OAuth client (type 3). Required by [google_sign_in] on Android so
  /// `authenticate()` returns an `idToken` for Firebase Auth.
  static const String googleServerClientId =
      '503588097549-cmbo7o55g9gur4pa86g9095mrvtd8msk.apps.googleusercontent.com';
}
